name: Maven CI

on:
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: PlantApp2/backend/plantapp

    steps:
      
    - uses: actions/checkout@v4

      
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: maven

      
    - run: chmod +x mvnw
    - run: ./mvnw clean verify
